language: python

python:
  - "2.7"
  - "3.6"

notifications:
  email: false

git:
  depth: 3

install:
  - pip install -r requirements.txt

script:
  python -m unittest discover -s tests -p "*_test.py"
