[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=pygfunction"
testpaths = [
    "tests",
]

[tool.coverage.run]
omit = ["pygfunction/_mpl.py"]
